name: Update README.md

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Build script
        run: python ./scripts/combine_sections.py

      - name: Commit and push
        env:
          CURRENT_BRANCH: ${{ github.ref_name }}
        if: success()
        run: |
          git config --global user.name "mdm-bot"
          git config --global user.email "mdm-bot@users.noreply.github.com"

          git add -f README.md

          if ! git diff --cached --quiet; then
            git commit -m "chore: updated 'README.md'"
            git push origin "$CURRENT_BRANCH"
          fi
